services:
  spaceship-ms:
    build: .
    image: spaceship-ms
    container_name: spaceship-ms
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:h2:mem:testdb
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=org.h2.Driver
      - SPRING_DATASOURCE_USERNAME=ro
      - SPRING_DATASOURCE_PASSWORD=pass



